version: '3.1'

services:
  account-frontend:
    build:
      context: ./account-frontend/
      dockerfile: Dockerfile
    volumes: # Volume binding
        - './account-frontend:/usr/src/app' 
    ports: 
        - "4200:4200" # Port mapping
    command: > 
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    networks:
      - back
  spring:
    build:
      context: ./account-backend
      dockerfile: Dockerfile
    ports:
      - 8081:8081
      - 8000:8000
    restart: "no"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/banque?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: nimporte
    networks:
      - back
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD=nimporte
      - MYSQL_DATABASE=banque
    ports:
      - 3336:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
     - back

  adminer:
    image: adminer
    restart: "no"
    depends_on:
      - db
    ports:
      - 8082:8080
    networks:
     - back


networks:
  back:

volumes:
  db-data: